# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('skillPlugin', '0004_skillcontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcontainer',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='skillcontainer',
            name='skills',
        ),
        migrations.DeleteModel(
            name='SkillContainer',
        ),
    ]
